version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: dw
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: manage.py
      FLASK_ENV: development
      DATABASE_URI: postgresql://user:secret@db:5432/dw
      JWT_SECRET_KEY: super-secret-key
    depends_on:
      db:
        condition: service_healthy    # <-- antes estaba mal indentado/mixeado con lista
      redis:
        condition: service_started
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - backend

volumes:
  db_data:
